# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d84c2aca00626066c1c8d81aa956ab22fefdae3d7362e324d495b90ca396c0dee6d2fbfcad806deaedcd3a2302a64033c5f15c2d1107f6a846209550cc8a18f

test:
  secret_key_base: f5b6fa2414a5b9d1075995f10c8d9ce0b22c25d56212bbaa13846d8f2795f34564e0bb187df77e24b4867a1c8103fad4cc2d8eca0a8d689146f2eab6a321bd64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
